src/main/java/com/github/wvengen/maven/proguard/ProGuardMojo.java, src/site/apt/index.apt
I changed the ProguardMojo.java to be able to change the names of the seeds and mapping filename. It should default to the previous filenames.
=> Adding the option to specify the mapping and seed file in the POM configuration

src/main/java/com/github/wvengen/maven/proguard/ProGuardMojo.java
They differ only by classifier, so factor that out
1/7th of #32
=> Consolidate the two attachArtifact calls

src/main/java/com/github/wvengen/maven/proguard/ProGuardMojo.java, src/site/apt/index.apt
In our project we have a quite long list of dependencies resulting in the command line to execute ProGaurd becoming too long. The list of `-libraryjars` is simple too long.
As a workaround I added the option `putLibraryJarsInTempDir` which makes the plugin copy all the library jars to a single temporary directory and pass that directory as the only `-libraryjars` argument to ProGuard. Build performance will be a bit worse, but the command line will be much shorter and I can build again.
=> Added option putLibraryJarsInTempDir

src/main/java/com/github/wvengen/maven/proguard/ProGuardMojo.java
This is a rework of the [pull-request 6](https://github.com/wvengen/proguard-maven-plugin/pull/6), but with a different approach. As there is only "dexguard" or "proguard", this might be covered by boolean-switch instead of failure-proven String-switch.
=> make it possible to use dexguard

src/main/java/com/github/wvengen/maven/proguard/ProGuardMojo.java
This is useful for when you need to use the latest beta version of
proguard that is not yet released on Maven central.
--------
I personally need this as 5.3 beta supports lambdas better.
Let me know if you have any feedback. Thanks!
=> Add the ability to specify an external proguard jar.

src/main/java/com/github/wvengen/maven/proguard/ProGuardMojo.java
This fixes #49.
To conserve the previous behaviour, remove possible already existing folder to avoid false-positives, but making it able to work when existing.
=> Bugfix issue49 tempfolder

src/main/java/com/github/wvengen/maven/proguard/ProGuardMojo.java
This fixes issue #55 by separating the attachment of the ProGuard map/seed files as artifacts from the attachment of the ProGuard jar artifact.
=> Fix #55 attach ProGuard map and seed files as artifacts if injar and outjar filename are the same.

src/main/java/com/github/wvengen/maven/proguard/Assembly.java, src/main/java/com/github/wvengen/maven/proguard/ProGuardMojo.java
Copy&Past from #65 
Hi.
I'm working with this plugin, but there is an embarrassing case in auto-completion (in my case, on eclipse).
In Assembly class, there is an inclusions list that is no typed.
This imply auto-completion not working because of raw type.
Anyway, in code, inclusions list is getted as an `List<Inclusion>` line 647-648 : https://github.com/wvengen/proguard-maven-plugin/blob/f0ec275312f039978fa0f46f3d2b497f66ad4101/src/main/java/com/github/wvengen/maven/proguard/ProGuardMojo.java#L646
https://github.com/wvengen/proguard-maven-plugin/blob/f0ec275312f039978fa0f46f3d2b497f66ad4101/src/main/java/com/github/wvengen/maven/proguard/ProGuardMojo.java#L647
Can you just change `List inclusions` to `List<Inclusion> inclusions` in Assembly class ? …
=> Assembly inclusions list generic

pom.xml
Simply use a newer proguard version. 
See https://github.com/wvengen/proguard-maven-plugin/issues/64
=> switch to proguard 6.0.3

src/main/java/com/github/wvengen/maven/proguard/ProGuardMojo.java
Since ProGuard supports [incremental obfuscation](https://www.guardsquare.com/proguard/manual/examples#incremental) by specifying `-applymapping`, I propose adding a functionality to incrementally obfuscate projects with multiple modules.
- `root:pom`
- `test1:jar`
- `test.Class1`
- `void method(test.Class1)`
- `test.Keep1`
- `test2:jar`
- `test.Class2`
- `void method(test.Class1)`
- `test.Keep2`
(An example of projects that actually work: [incremental-obfuscation.zip](https://github.com/wvengen/proguard-maven-plugin/files/2025747/incremental-obfuscation.zip))
In the project of the above layout, If you specify `proguard_map.txt` which is the result of obfuscating `test1:jar` with `-applymapping` when obfuscating `test2:jar`, ProGuard will consider the result of changing the identifier in …
=> Incremental obfuscation functionality

pom.xml, src/it/simple/pom.xml
Updates Java source and target to 1.6. Before this change the code didn't actually compile with the latest Maven versions (at least 3.5.0+).
=> Bump used Java version to 1.6

.gitignore, pom.xml
Fixes #86 
After this change, the deployment can be done with "mvn clean deploy -P=release" if gpg-agent is running on the machine and suitable credentials are found in settings.xml.
=> Add distribution management

pom.xml, src/main/java/com/github/wvengen/maven/proguard/ProGuardMojo.java
If found library is a directory, copy it as such, not as a file as previously has been done.
Also adds some debug log statements.
Also now throws MojoFailureException if deleting the temporary directory fails.
Fixes https://github.com/wvengen/proguard-maven-plugin/issues/92
=> Issue-92: If found library is a directory, copy it as such

pom.xml
6.1.1 is currently the latest released version and supports Java versions up to 12.
Fixes #64
=> Issue-64: Update default Proguard version to 6.1.1

pom.xml, src/main/java/com/github/wvengen/maven/proguard/ProGuardMojo.java
Proguard 7 requires two JARs on the classpath: proguard-base and proguard-core.
=> Proguard7 fix

src/main/java/com/github/wvengen/maven/proguard/ProGuardMojo.java
I need to add jackson to my project but I there are some files I don't want to be included in the final jar. This pull request addresses the fact that filter is beeing ignored on libraries.
I tested the code and verified that the filter is now working.
Example pom:
```
<inclusion>
<groupId>com.fasterxml.jackson.core</groupId>
<artifactId>jackson-databind</artifactId>
<filter>!META-INF/maven/**,!META-INF/LICENSE,!META-INF/MANIFEST.MF,!META-INF/NOTICE</filter>
<library>true</library>
</inclusion>
```
=> Respect filter on library merge

pom.xml, src/main/java/com/github/wvengen/maven/proguard/ProGuardMojo.java
Maybe this fixes https://github.com/wvengen/proguard-maven-plugin/issues/112
I added a warning if a dependency is defined twice. This can happen if you do not define proguardVersion but you add a dependency for a different proguard version. The default version of proguard is defined in pom.xml and I did'nt want to define it in java too. If it is possible to get the version out of the pom and into the mojo, I'm happy to add this.
I did different tests with defined and not defined proguardVersion and dependency and no dependency. Everything is working fine now.
=> Fixed ProGuard 7 not finding classes

src/main/java/com/github/wvengen/maven/proguard/ProGuardMojo.java, src/site/apt/index.apt
``putLibraryJarsInTempDir`` did not work for me. My project had to many -injars, not libraries.
This pull request introduces a new option ``generateTemporaryConfigurationFile`` that generates a temporary proguard configuration file that includes all arguments.
The pull request does not modify other options.
fixes #113
=> added generateTemporaryConfigurationFile option

pom.xml, src/main/java/com/github/wvengen/maven/proguard/ProGuardMojo.java
#127 
Bump minimum Java version to 1.8.
Fix broken close call by using try-with-resources.
=> Issue #127: Bump minimum Java version to 1.8

pom.xml
Fixes #142 
Update Proguard to 7.2.0-beta2.
This should have Java 17 support.
=> Issue #142: Update Proguard to 7.2.0-beta2

pom.xml
Fixes #130 
Fix site generation by updating dependencies.
Also license -> licenses is rerequired.
=> Issue #130: Documentation site broken

src/it/simple/pom.xml, src/it/simple/proguard.conf, src/main/java/com/github/wvengen/maven/proguard/ProGuardMojo.java
Fixes #161 
Fix missing transitive dependencies from classpath when executing Proguard.
=> Issue #161: ITs fail on Java 11
